#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("O8.Mobile.Droid.Vault.Tests.Resource", IsApplication=true)]

namespace O8.Mobile.Droid.Vault.Tests
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::Nunit.Runner.Resource.String.ApplicationName = global::O8.Mobile.Droid.Vault.Tests.Resource.String.ApplicationName;
			global::Nunit.Runner.Resource.String.Hello = global::O8.Mobile.Droid.Vault.Tests.Resource.String.Hello;
			global::O8.Mobile.Droid.Vault.Resource.String.library_name = global::O8.Mobile.Droid.Vault.Tests.Resource.String.library_name;
			global::Xamarin.Forms.Platform.Resource.String.ApplicationName = global::O8.Mobile.Droid.Vault.Tests.Resource.String.ApplicationName;
			global::Xamarin.Forms.Platform.Resource.String.Hello = global::O8.Mobile.Droid.Vault.Tests.Resource.String.Hello;
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f020000
			public const int Main = 2130837504;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f030001
			public const int ApplicationName = 2130903041;
			
			// aapt resource value: 0x7f030000
			public const int Hello = 2130903040;
			
			// aapt resource value: 0x7f030003
			public const int app_name = 2130903043;
			
			// aapt resource value: 0x7f030002
			public const int library_name = 2130903042;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
